### ISSUE TITLE
Version 4.10.0 destroy() method throws DOM not defined exception

### ISSUE THREAD

**Issue by spazard1** [yairEO/tagify#1008]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://codesandbox.io/s/tagify-react-issue-template-forked-4i1gi8?file=/package.json
**Click the "destroy" button on this sandbox to unmount the Tags component and see the exception in the console.**

### Explanation

- **What is the expected behavior?**
Tags function component is correctly unmounted

- **What is happening instead?**
Exception is thrown saying "DOM is not defined."

- **What error message are you getting?**
react-dom.development.js:22670 Uncaught ReferenceError: DOM is not defined
    at Tagify.destroy (tagify.js:2286:1)
    at react.tagify.js:26:1
    at safelyCallDestroy (react-dom.development.js:22768:1)
    at commitHookEffectListUnmount (react-dom.development.js:22932:1)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:24874:1)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:24824:1)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24732:1)
    at commitPassiveUnmountEffects (react-dom.development.js:24717:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26847:1)
    at flushPassiveEffects (react-dom.development.js:26801:1)

**Comment by spazard1** [comment]
Caused by this commit: https://github.com/yairEO/tagify/commit/cba082cdc183d324632d17e36fc1bb418fd84e19
