### ISSUE TITLE
Integrate with jquery database tagify throwing error

### ISSUE THREAD

**Issue by vireddy87** [yairEO/tagify#1088]
We have jquery datatable which as textarea. Textarea uses tagify everything works fine until we do a datatable row submit get error 
core.mjs:6494 ERROR TypeError: Cannot read properties of null (reading ‘removeChild’)
    at M.destroy (tagify.min.js:26:36936)
    at M.observeOriginalInputValue (tagify.min.js:26:26616)
    at timer (zone.js:2405:41)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25595:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at invokeTask (zone.js:487:34)
    at ZoneTask.invoke (zone.js:476:48)
    at data.args.<computed> (zone.js:2385:32)

code that adds tags to textarea ( there is one per row in datagrid)
		jQuery('textarea').each(
			function (i, val) {
				this.tagify = new Tagify(val, {
					enforceWhitelist: true,
					delimiters: ",",
					keepInvalidTags: true,
					whitelist: acquisitions,
					id: val.name,
					dropdown: {
						position: "input",
						enabled: 0 // always opens dropdown when input gets focus
					},
					callbacks: {
						add: console.log,  // callback when adding a tag
						remove: console.log,   // callback when removing a tag
					}
				});

			});

	}

**Comment by yairEO** [comment]
please edit your ticket..  have you seen how this looks? I cannot read or understand anything

**Comment by vireddy87** [comment]
I have update content issue with using datatable with tagify

**Comment by yairEO** [comment]
Please create a minimal jsbin demo page so I could investigate
