### ISSUE TITLE
tagify:26 Uncaught TypeError: g.hasAttribute is not a function on Android

### ISSUE THREAD

**Issue by pavel-nitka** [yairEO/tagify#1154]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page

https://jsbin.com/rugeqoleri/1/edit?html,js,output

### Explanation

1. open in Chrome on Android device
2. type any text
3. select all
4. press 'Backspace'

- **What is the expected behavior?**
No error
- **What is happening instead?**
Error
- **What error message are you getting?**
```
tagify:26 Uncaught TypeError: g.hasAttribute is not a function
    at N.onKeydown (tagify:26:24218)
    at N.onMixTagsInput (tagify:26:27155)
    at N.onInput (tagify:26:26458)
```
Unminified:
```
core.mjs:7643 ERROR TypeError: isCaretAfterTag.hasAttribute is not a function
    at Tagify.onKeydown (tagify.min.js:1524:40)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26278:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
    at HTMLSpanElement.globalZoneAwareCallback (zone.js:1725:16)
```

I think issue is this code it not looks quite correct 
![image](https://user-images.githubusercontent.com/43527493/204196510-103ff3f0-b212-4cac-b028-66c12f37a47c.png)

isCaretAfterTag - has bool type and therefore doesn't have hasAttribute function

**Comment by pavel-nitka** [comment]
Thank you for fix but it not fixed all cases. At android error still presents. You fixed case 1 but how you can see at screenshot case 2 still throws error

![image](https://user-images.githubusercontent.com/43527493/205476928-0d2eb8d3-9246-48e3-a0e9-f10bb4f08b86.png)

**Comment by yairEO** [comment]
Miss that, sorry. will push a new fix

**Comment by pavel-nitka** [comment]
@yairEO I have got new error because 'e' doesn't have 'preventDefault' method.

core.mjs:7629 ERROR TypeError: e.preventDefault is not a function
    at Tagify.onKeydown (tagify.min.js:1576:21)
    at Tagify.onMixTagsInput (tagify.min.js:1755:43)
    at Tagify.onInput (tagify.min.js:1702:75)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26254:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
![image](https://user-images.githubusercontent.com/43527493/205527700-f968956d-116c-4a6f-8558-773eee349fd1.png)

I can create PR to fix this but I do not have access to push new branch in this repos

**Comment by yairEO** [comment]
I will handle it once I get back home in 9 hours or so

**Comment by pavel-nitka** [comment]
@yairEO do you have any update for this? If you busy I can create PR by myself (just give me right to create branch and PR in this repos). Thank you.

**Comment by robtextrequest** [comment]
@yairEO This doesn't appear to be resolved. Can you take another look, or allow @pavel-nitka to create a PR?

We appreciate this project and all you do!
